# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-25 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_tags'),
        ('accounts', '0007_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
