# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, choices=[('Events', 'Events'), ('General Discussion', 'General Discussion')], max_length=30, null=True),
        ),
    ]
