# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
