# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-10 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_postcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postComment',
            new_name='Comment',
        ),
    ]
