# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-04 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200603_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
