# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-19 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Website Development', 'Website Development'), ('Social Media Management', 'Social Media Management'), ('Website Traffic', 'Website Traffic Increase')], default='', max_length=25),
        ),
    ]
