# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-04 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creator_id',
        ),
    ]
