# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-04 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creator_id',
            new_name='prod_creator_id',
        ),
    ]
