# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-04 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_remove_product_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
